version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: ddb-host
    container_name: ddb-run
    ports:
      - "9400:8000"
  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: es-run
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    environment:
      - discovery.type=single-node
networks:
  elastic:
    driver: bridge