development:
  SECRET_KEY: "anVtYmFsYWthanVtYmFsYWthanVtYmFsYWp1bWJhbGU="
  PASSWORD: "onrailsin"
  DOMAIN: "http://localhost:8000"
  ES_URI: "http://localhost:9200"
  AWS_ACCESS_KEY: "OnRails"
  AWS_SECRET_KEY: "onrailsin"
  AWS_REGION: "asia-pacific-3"
  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: 6379
  REDIS_PASSWORD: "onrailsin"
  DYNAMO_URL: "http://localhost:9400"
staging:
  DOMAIN: "http://localhost:8000"
  ES_URI: "http://localhost:9200"